DWAPlannerROS:

  max_vel_x: 1.5
  min_vel_x: -0.2
  min_vel_y: 0.0
  max_vel_y: 0.0
  max_vel_z: 0.0
  min_vel_z: 0.0

  max_vel_trans: 1.5
  min_vel_trans: 0.1

  max_vel_theta: 0.3
  min_vel_theta: 0.1

  acc_lim_x: 10.0
  acc_lim_theta: 5.0

  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  latch_xy_goal_tolerance: false

  sim_time: 3.0
  vx_samples: 15
  vy_samples: 1
  vth_samples: 30

  path_distance_bias: 25.0
  goal_distance_bias: 25.0
  occdist_scale: 0.2
  forward_point_distance: 0.3

  holonomic_robot: false