local_costmap:
  global_frame: world
  robot_base_frame: rexrov2/base_link
  update_frequency: 10.0
  publish_frequency: 5.0

  rolling_window: true
  width: 30.0
  height: 30.0
  resolution: 0.1

  plugins:
   - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
   - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}