shutdown_costmaps: false
controller_frequency: 5.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 3.0
planner_frequency: 1.0
oscillation_timeout: 10.0
oscillation_distance: 0.2

max_rot_vel: 0.3
min_in_place_rotational_vel: 0.1

acc_lim_theta: 0.5
acc_lim_th: 0.5           # 有些版本用这个名字，两个都写上保险